### PR TITLE
modification to monitor git submodules and depend on multi flavor and build assemble task

### PR DESCRIPTION
**Pull request by yunarta**
You plugin is great, but i need more function for submodules.
This is my modification.

### CODE REVIEW

**Comment by selesse** [comment]
Hey, thanks for the feedback and contribution. :)

I'm all for running the Git commands on the project root directory.

For your change to the `assemble` task hook, could you achieve the functionality you want by applying the plugin to all of your submodules?

In other words, your root `build.gradle` would have:

``` groovy
subprojects {
    apply plugin: 'com.selesse.git.changelog'
}
```

If you do this, it should create a `generateChangelog` task for all modules, including non-Java ones. 

Thanks!

**Comment by yunarta** [comment]
the assemble need to be changed because you only add it to depends on "assemble", while my android project, I created a combination of product flavor and built variant.

And i used your plugin with my versioning plugin and in the current project set up, i don't run "assemble", but run the variant instead.

By the way, the change log generation part. When i tagged the latest commit then I got nothing. If i run your plugin before tagging the latest commit, then I got "Unreleased". What should come of out of course all commit message up to the last tagged commit

**Comment by selesse** [comment]
I'd rather specifically hook into the Android tasks separately. I want users to enable the plugin for specific modules, but not be forced to use it for all modules. 

I'm trying to figure out what would make the most sense here. I've started work on [an Android branch](https://github.com/selesse/gradle-git-changelog/tree/android) -- the logic for hooking into the different build variants can be found [here](https://github.com/selesse/gradle-git-changelog/commit/13e422f1d334363f7290864b0b872f3ef7a33fcb#diff-4d15199e2f67567b8eb514c6784c0e23R41).

**Comment by yunarta** [comment]
Oh. Now i see where you coming at.
Let met explain my usage to you.

I do put your plugin in subproject build.gradle.
I think you miss-understood my intention about this changes.

Here are snippets of my build.gradle

```
android {
    productFlavors {
        playStore {
            ext.betaDistributionEmailsFilePath = new File(projectDir, "beta/playstore_list.txt").absolutePath        
        }

        adHoc {
            ext.betaDistributionEmailsFilePath = new File(projectDir, "beta/adhoc_list.txt").absolutePath
        }
    }

    buildTypes {
        release {
        }

        fabric {
            initWith(buildTypes.debug)
        }

        jenkins {
            initWith(buildTypes.debug)
            ext.betaDistributionReleaseNotesFilePath = new File(projectDir, "beta/CHANGELOG.md").absolutePath
        }
    }
}
```

What will happen in Android, Gradle will create
- assemblePlayStoreDebug
- assemblePlayStoreRelease
- assemblePlayStoreFabric
- assemblePlayStoreJenkins
- assembleAdHocDebug
- assembleAdHocRelease
- assembleAdHocFabric
- assembleAdHocJenkins

How currently I build this project is by invoking one assemble task at a time.
However your code in GitLogPlugin.groovy only attach to 'assemble' task, thus when i call assemblePlayStoreRelease, it would not generate the change log.

**Comment by selesse** [comment]
OK, I think I understand now, thanks for clearing that up.

What if, for Android plugins, I hooked into tasks that started with `assemble` like this:

``` groovy
if (hasAndroidPlugin()) {
    project.plugins.withType(getAndroidPlugin()) {
        logger.info("Configuring Android plugin")
        project.tasks.findAll { t -> t.name.startsWith('assemble') }.each {
            it.dependsOn(task)
        }
    }
}
```

Would that satisfy your use case?

**Comment by yunarta** [comment]
That what i did in my fork, and i published to jCenter for my own usage for now :)

I'm not so familiar with how Gradle and groovy scripting, but i found that if i didn't call like these below.
It will fail the build test

```
project.tasks.getByName("assemble")
project.tasks.findAll { t -> t.name.startsWith('assemble') }.each {
    it.dependsOn(task)
}
```

**Comment by selesse** [comment]
OK, I'll look into it. Would you be OK with rebasing to only include the change to run the Git commands in the project root directory so I can merge that in?

I'll create separate issues for the `assemble` Android hook and the other issue you reported earlier.

**Comment by yunarta** [comment]
sure. i will clean up the code and usage as well. yesterday i just created what i requires to have :)

**Pull request closed without merging**
